### ISSUE TITLE
Bound is not correct in JSON

### ISSUE THREAD

**Issue by AAAstorga** [cuappdev/tcat-backend#5]
`"location" : [
        42.447613,
        -76.48205799999999
      ],
      "bound" : "north",
      "arrivalTime" : "5:20 AM",
      "time" : "5:03 AM",
      "routeNumber" : 81,
      "stops" : [
        "Uris Hall Across Street",
        "A Lot",
        "Uris Hall"
      ]`

I was not under the impression that a bound could be `north`. I believe @mattbarker016 only accounts for inbound and outbound and loop? What are all the possible bounds?

**Comment by mattbarker016** [comment]
It should only be inbound or outbound. We actually don't even display the bound in the app currently, so you can ignore it 🙃
